dist: xenial
branches:
  only:
  - master

before_script:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Linux-64bit.deb
  - sudo dpkg -i hugo_0.54.0_Linux-64bit.deb
  - rm -rf public 2> /dev/null

script:
    - hugo

deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  keep-history: true
  target-branch: gh-pages
  fqdn: xdev.ma
  email: $GITHUB_EMAIL
  name: $GITHUB_USERNAME
  on:
    branch: master