dist: xenial
branches:
  only:
  - master

before_script:
  - sudo apt-get update
  - sudo apt-get install -y hugo
  - rm -rf public 2> /dev/null

script:
    - hugo

deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  keep-history: true
  target-branch: gh-pages
  fqdn: xdev.ma
  email: $GITHUB_EMAIL
  name: $GITHUB_USERNAME
  on:
    branch: master